/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 earth-optimized.glb 
Author: AirStudios (https://sketchfab.com/sebbe613)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-5f9c35be31a047928eace8b415a8ee3a
Title: Earth
*/

import { useRef, type JSX } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    pSphere1_phong1_0: THREE.Mesh;
    pSphere1_phong1_0_1: THREE.Mesh;
    pSphere4_lambert6_0: THREE.Mesh;
    pSphere4_lambert6_0_1: THREE.Mesh;
    pSphere5_lambert7_0: THREE.Mesh;
    pSphere5_lambert7_0_1: THREE.Mesh;
  };
  materials: {
    phong1: THREE.MeshPhongMaterial;
    lambert6: THREE.MeshLambertMaterial;
    lambert7: THREE.MeshLambertMaterial;
  };
};

export default function Earth(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./Earth/earth-optimized.glb",
  ) as unknown as GLTFResult;
  const earthRef = useRef<THREE.Group>(null);

  useFrame(() => {
    if (earthRef.current) {
      earthRef.current.rotation.x += 0.000173;
      earthRef.current.rotation.y += 0.00001;
    }
  });
  return (
    <group {...props} dispose={null} ref={earthRef}>
      <group scale={96.724}>
        <mesh
          geometry={nodes.pSphere1_phong1_0.geometry}
          material={materials.phong1}
        />
        <mesh
          geometry={nodes.pSphere1_phong1_0_1.geometry}
          material={materials.phong1}
        />
      </group>
      <group scale={97.464}>
        <mesh
          geometry={nodes.pSphere4_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          geometry={nodes.pSphere4_lambert6_0_1.geometry}
          material={materials.lambert6}
        />
      </group>
      <group scale={98.098}>
        <mesh
          geometry={nodes.pSphere5_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.pSphere5_lambert7_0_1.geometry}
          material={materials.lambert7}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./Earth/earth-optimized.glb");
