/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 source/toy_cat.glb 
Author: BAMEN (https://sketchfab.com/bamenwo05)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toy-cat-f04d46d26172423688e3f64f72c99bad
Title: Toy Cat
*/

import { useRef, type JSX } from "react";
import { Sphere, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import type { GLTF } from "three/examples/jsm/Addons.js";

type GLTFResult = GLTF & {
  nodes: {
    Toy_Cat_Toy_Cat_Material_0: THREE.Mesh;
  };
  materials: {
    Toy_Cat_Material: THREE.Material;
  };
};

export default function ToyCat(props: JSX.IntrinsicElements["group"]) {
  const catRef = useRef<THREE.Group>(null);

  useFrame((_state, delta) => {
    if (catRef.current) {
      catRef.current.rotation.x -= delta / 10;
      catRef.current.rotation.y -= delta / 15;
    }
  });

  const { nodes, materials } = useGLTF(
    "./Cat/source/toy_cat.glb",
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} ref={catRef}>
          <mesh
            geometry={nodes.Toy_Cat_Toy_Cat_Material_0.geometry}
            material={materials.Toy_Cat_Material}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />

          {/* Glass helmet — nested here so it inherits the cat's transform/scale and moves with it */}
          <Sphere args={[50, 64, 64]} position={[-10, 200, 0]}>
            <meshPhysicalMaterial
              // roughness={0}
              transmission={1}
              thickness={0.2}
              ior={1}
              envMapIntensity={1}
              clearcoat={1}
              clearcoatRoughness={0}
              transparent
              opacity={1}
              side={2} // render both faces so you can see the far wall of the helmet through the near one
            />
          </Sphere>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./Cat/source/toy_cat.glb");
